[package]
name = "byte_str"
version = "0.1.0"
authors = ["Eduardo Sánchez Muñoz <esm@eduardosm.net>"]
description = "Wrapper types around [u8] and Vec<u8> with similar functionality as str and String"
license = "MIT/Apache-2.0"

[features]
no_std = []

[dependencies]
